// <auto-generated />
using System;
using EspacoVerde.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EspacoVerde.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250528114911_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EspacoVerde.Models.Residuo", b =>
                {
                    b.Property<int>("ID_Residuo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Residuo"));

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioID_Usuario")
                        .HasColumnType("int");

                    b.HasKey("ID_Residuo");

                    b.HasIndex("UsuarioID_Usuario");

                    b.ToTable("Residuos");
                });

            modelBuilder.Entity("EspacoVerde.Models.Transacao", b =>
                {
                    b.Property<int>("ID_Transacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Transacao"));

                    b.Property<DateTime>("Data_Transacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Comprador")
                        .HasColumnType("int");

                    b.Property<int>("ID_Residuo")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco_Final")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Transacao");

                    b.HasIndex("ID_Comprador");

                    b.HasIndex("ID_Residuo")
                        .IsUnique();

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("EspacoVerde.Models.Usuario", b =>
                {
                    b.Property<int>("ID_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Usuario"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID_Usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EspacoVerde.Models.Residuo", b =>
                {
                    b.HasOne("EspacoVerde.Models.Usuario", "Usuario")
                        .WithMany("Residuos")
                        .HasForeignKey("UsuarioID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EspacoVerde.Models.Transacao", b =>
                {
                    b.HasOne("EspacoVerde.Models.Usuario", "Comprador")
                        .WithMany("TransacoesComoComprador")
                        .HasForeignKey("ID_Comprador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EspacoVerde.Models.Residuo", "Residuo")
                        .WithOne("Transacao")
                        .HasForeignKey("EspacoVerde.Models.Transacao", "ID_Residuo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Residuo");
                });

            modelBuilder.Entity("EspacoVerde.Models.Residuo", b =>
                {
                    b.Navigation("Transacao")
                        .IsRequired();
                });

            modelBuilder.Entity("EspacoVerde.Models.Usuario", b =>
                {
                    b.Navigation("Residuos");

                    b.Navigation("TransacoesComoComprador");
                });
#pragma warning restore 612, 618
        }
    }
}
