// <auto-generated />
using System;
using EspacoVerde.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EspacoVerde.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250531194718_InitAna")]
    partial class InitAna
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EspacoVerde.Models.Localizacao", b =>
                {
                    b.Property<int>("ID_Localizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Localizacao"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Localizacao");

                    b.ToTable("Localizacoes");

                    b.HasData(
                        new
                        {
                            ID_Localizacao = 1,
                            Cidade = "Araraquara",
                            Estado = "SP"
                        },
                        new
                        {
                            ID_Localizacao = 2,
                            Cidade = "Matão",
                            Estado = "SP"
                        },
                        new
                        {
                            ID_Localizacao = 3,
                            Cidade = "São Carlos",
                            Estado = "SP"
                        },
                        new
                        {
                            ID_Localizacao = 4,
                            Cidade = "Ribeirão Preto",
                            Estado = "SP"
                        });
                });

            modelBuilder.Entity("EspacoVerde.Models.Residuo", b =>
                {
                    b.Property<int>("ID_Residuo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Residuo"));

                    b.Property<int>("ID_Localizacao")
                        .HasColumnType("int");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Residuo");

                    b.HasIndex("ID_Localizacao");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("Residuos");

                    b.HasData(
                        new
                        {
                            ID_Residuo = 1,
                            ID_Localizacao = 1,
                            ID_Usuario = 1,
                            ImgUrl = "aco_inox.webp",
                            Nome = "Aço Inox",
                            PrecoKg = 5.50m,
                            Quantidade = 100m
                        },
                        new
                        {
                            ID_Residuo = 2,
                            ID_Localizacao = 2,
                            ID_Usuario = 1,
                            ImgUrl = "ferro_fundido.webp",
                            Nome = "Ferro Fundido",
                            PrecoKg = 1.20m,
                            Quantidade = 50m
                        },
                        new
                        {
                            ID_Residuo = 3,
                            ID_Localizacao = 3,
                            ID_Usuario = 1,
                            ImgUrl = "aluminio.webp",
                            Nome = "Alumínio",
                            PrecoKg = 3.80m,
                            Quantidade = 75m
                        },
                        new
                        {
                            ID_Residuo = 4,
                            ID_Localizacao = 4,
                            ID_Usuario = 1,
                            ImgUrl = "cobre.webp",
                            Nome = "Cobre",
                            PrecoKg = 8.20m,
                            Quantidade = 30m
                        },
                        new
                        {
                            ID_Residuo = 5,
                            ID_Localizacao = 1,
                            ID_Usuario = 1,
                            ImgUrl = "latao.webp",
                            Nome = "Latão",
                            PrecoKg = 4.50m,
                            Quantidade = 60m
                        },
                        new
                        {
                            ID_Residuo = 6,
                            ID_Localizacao = 2,
                            ID_Usuario = 1,
                            ImgUrl = "zinco.webp",
                            Nome = "Zinco",
                            PrecoKg = 2.10m,
                            Quantidade = 40m
                        },
                        new
                        {
                            ID_Residuo = 7,
                            ID_Localizacao = 3,
                            ID_Usuario = 1,
                            ImgUrl = "chumbo.webp",
                            Nome = "Chumbo",
                            PrecoKg = 1.80m,
                            Quantidade = 25m
                        },
                        new
                        {
                            ID_Residuo = 9,
                            ID_Localizacao = 1,
                            ID_Usuario = 1,
                            ImgUrl = "niquel.webp",
                            Nome = "Níquel",
                            PrecoKg = 12.00m,
                            Quantidade = 10m
                        },
                        new
                        {
                            ID_Residuo = 10,
                            ID_Localizacao = 2,
                            ID_Usuario = 1,
                            ImgUrl = "titanio.webp",
                            Nome = "Titânio",
                            PrecoKg = 25.00m,
                            Quantidade = 5m
                        },
                        new
                        {
                            ID_Residuo = 11,
                            ID_Localizacao = 3,
                            ID_Usuario = 1,
                            ImgUrl = "bronze.webp",
                            Nome = "Bronze",
                            PrecoKg = 6.80m,
                            Quantidade = 12m
                        },
                        new
                        {
                            ID_Residuo = 12,
                            ID_Localizacao = 4,
                            ID_Usuario = 1,
                            ImgUrl = "aco_carbono.webp",
                            Nome = "Aço Carbono",
                            PrecoKg = 0.90m,
                            Quantidade = 22m
                        },
                        new
                        {
                            ID_Residuo = 13,
                            ID_Localizacao = 1,
                            ID_Usuario = 1,
                            ImgUrl = "magnesio.webp",
                            Nome = "Magnésio",
                            PrecoKg = 4.20m,
                            Quantidade = 18m
                        },
                        new
                        {
                            ID_Residuo = 14,
                            ID_Localizacao = 2,
                            ID_Usuario = 1,
                            ImgUrl = "cromo.webp",
                            Nome = "Cromo",
                            PrecoKg = 7.10m,
                            Quantidade = 16m
                        },
                        new
                        {
                            ID_Residuo = 15,
                            ID_Localizacao = 3,
                            ID_Usuario = 1,
                            ImgUrl = "manganes.webp",
                            Nome = "Manganês",
                            PrecoKg = 1.50m,
                            Quantidade = 20m
                        },
                        new
                        {
                            ID_Residuo = 17,
                            ID_Localizacao = 1,
                            ID_Usuario = 1,
                            ImgUrl = "molibdenio.webp",
                            Nome = "Molibdênio",
                            PrecoKg = 28.00m,
                            Quantidade = 2m
                        },
                        new
                        {
                            ID_Residuo = 18,
                            ID_Localizacao = 2,
                            ID_Usuario = 1,
                            ImgUrl = "vanadio.webp",
                            Nome = "Vanádio",
                            PrecoKg = 15.50m,
                            Quantidade = 7m
                        },
                        new
                        {
                            ID_Residuo = 19,
                            ID_Localizacao = 3,
                            ID_Usuario = 1,
                            ImgUrl = "aco_inox.webp",
                            Nome = "Aço Inox",
                            PrecoKg = 5.70m,
                            Quantidade = 15m
                        },
                        new
                        {
                            ID_Residuo = 20,
                            ID_Localizacao = 4,
                            ID_Usuario = 1,
                            ImgUrl = "aluminio.webp",
                            Nome = "Alumínio",
                            PrecoKg = 4.00m,
                            Quantidade = 50m
                        });
                });

            modelBuilder.Entity("EspacoVerde.Models.Transacao", b =>
                {
                    b.Property<int>("ID_Transacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Transacao"));

                    b.Property<DateTime>("Data_Transacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Comprador")
                        .HasColumnType("int");

                    b.Property<int>("ID_Residuo")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco_Final")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Transacao");

                    b.HasIndex("ID_Comprador");

                    b.HasIndex("ID_Residuo")
                        .IsUnique();

                    b.ToTable("Transacoes");

                    b.HasData(
                        new
                        {
                            ID_Transacao = 1,
                            Data_Transacao = new DateTime(2025, 5, 31, 16, 47, 18, 142, DateTimeKind.Local).AddTicks(147),
                            ID_Comprador = 2,
                            ID_Residuo = 1,
                            Preco_Final = 550m
                        });
                });

            modelBuilder.Entity("EspacoVerde.Models.Usuario", b =>
                {
                    b.Property<int>("ID_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Usuario"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID_Usuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            ID_Usuario = 1,
                            CNPJ = "12.345.678/0001-99",
                            Email = "alfa@email.com",
                            RazaoSocial = "Metalúrgica Alfa",
                            Senha = "123",
                            Status = true
                        },
                        new
                        {
                            ID_Usuario = 2,
                            CNPJ = "98.765.432/0001-11",
                            Email = "beta@email.com",
                            RazaoSocial = "Siderúrgica Beta",
                            Senha = "123",
                            Status = true
                        });
                });

            modelBuilder.Entity("EspacoVerde.Models.Residuo", b =>
                {
                    b.HasOne("EspacoVerde.Models.Localizacao", "Localizacao")
                        .WithMany("Residuos")
                        .HasForeignKey("ID_Localizacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EspacoVerde.Models.Usuario", "Usuario")
                        .WithMany("Residuos")
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localizacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EspacoVerde.Models.Transacao", b =>
                {
                    b.HasOne("EspacoVerde.Models.Usuario", "Comprador")
                        .WithMany("TransacoesComoComprador")
                        .HasForeignKey("ID_Comprador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EspacoVerde.Models.Residuo", "Residuo")
                        .WithOne("Transacao")
                        .HasForeignKey("EspacoVerde.Models.Transacao", "ID_Residuo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Residuo");
                });

            modelBuilder.Entity("EspacoVerde.Models.Localizacao", b =>
                {
                    b.Navigation("Residuos");
                });

            modelBuilder.Entity("EspacoVerde.Models.Residuo", b =>
                {
                    b.Navigation("Transacao")
                        .IsRequired();
                });

            modelBuilder.Entity("EspacoVerde.Models.Usuario", b =>
                {
                    b.Navigation("Residuos");

                    b.Navigation("TransacoesComoComprador");
                });
#pragma warning restore 612, 618
        }
    }
}
