// <auto-generated />
using System;
using EspacoVerde.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EspacoVerde.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EspacoVerde.Models.Residuo", b =>
                {
                    b.Property<int>("ID_Residuo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Residuo"));

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Residuo");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("Residuos");

                    b.HasData(
                        new
                        {
                            ID_Residuo = 1,
                            ID_Usuario = 1,
                            ImgUrl = "aco_Inox.jpeg",
                            Nome = "Aço Inox",
                            Quantidade = 100m
                        },
                        new
                        {
                            ID_Residuo = 2,
                            ID_Usuario = 1,
                            ImgUrl = "Ferro_Fundido.jpeg",
                            Nome = "Ferro Fundido",
                            Quantidade = 50m
                        });
                });

            modelBuilder.Entity("EspacoVerde.Models.Transacao", b =>
                {
                    b.Property<int>("ID_Transacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Transacao"));

                    b.Property<DateTime>("Data_Transacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Comprador")
                        .HasColumnType("int");

                    b.Property<int>("ID_Residuo")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco_Final")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Transacao");

                    b.HasIndex("ID_Comprador");

                    b.HasIndex("ID_Residuo")
                        .IsUnique();

                    b.ToTable("Transacoes");

                    b.HasData(
                        new
                        {
                            ID_Transacao = 1,
                            Data_Transacao = new DateTime(2025, 5, 28, 10, 23, 9, 596, DateTimeKind.Local).AddTicks(1976),
                            ID_Comprador = 2,
                            ID_Residuo = 1,
                            Preco_Final = 1500m
                        });
                });

            modelBuilder.Entity("EspacoVerde.Models.Usuario", b =>
                {
                    b.Property<int>("ID_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Usuario"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID_Usuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            ID_Usuario = 1,
                            CNPJ = "12.345.678/0001-99",
                            Email = "alfa@email.com",
                            RazaoSocial = "Metalúrgica Alfa",
                            Senha = "123",
                            Status = true
                        },
                        new
                        {
                            ID_Usuario = 2,
                            CNPJ = "98.765.432/0001-11",
                            Email = "beta@email.com",
                            RazaoSocial = "Siderúrgica Beta",
                            Senha = "123",
                            Status = true
                        });
                });

            modelBuilder.Entity("EspacoVerde.Models.Residuo", b =>
                {
                    b.HasOne("EspacoVerde.Models.Usuario", "Usuario")
                        .WithMany("Residuos")
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EspacoVerde.Models.Transacao", b =>
                {
                    b.HasOne("EspacoVerde.Models.Usuario", "Comprador")
                        .WithMany("TransacoesComoComprador")
                        .HasForeignKey("ID_Comprador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EspacoVerde.Models.Residuo", "Residuo")
                        .WithOne("Transacao")
                        .HasForeignKey("EspacoVerde.Models.Transacao", "ID_Residuo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Residuo");
                });

            modelBuilder.Entity("EspacoVerde.Models.Residuo", b =>
                {
                    b.Navigation("Transacao")
                        .IsRequired();
                });

            modelBuilder.Entity("EspacoVerde.Models.Usuario", b =>
                {
                    b.Navigation("Residuos");

                    b.Navigation("TransacoesComoComprador");
                });
#pragma warning restore 612, 618
        }
    }
}
